<?php

namespace App\Models;

use Database\Factories\GenerationJobFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class GenerationJob extends Model
{
    /** @use HasFactory<GenerationJobFactory> */
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'user_id',
        'workflow_template_id',
        'type',
        'status',
        'input_json',
        'resolved_workflow_json',
        'comfy_prompt_id',
        'error_message',
        'started_at',
        'finished_at',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'input_json' => 'array',
            'resolved_workflow_json' => 'array',
            'started_at' => 'datetime',
            'finished_at' => 'datetime',
        ];
    }

    /**
     * Get the user that owns this job.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the workflow template used for this job.
     */
    public function workflowTemplate(): BelongsTo
    {
        return $this->belongsTo(WorkflowTemplate::class);
    }

    /**
     * Get the assets generated by this job.
     */
    public function assets(): HasMany
    {
        return $this->hasMany(GenerationAsset::class);
    }

    /**
     * Get the events for this job.
     */
    public function events(): HasMany
    {
        return $this->hasMany(GenerationJobEvent::class)->orderBy('created_at');
    }

    /**
     * Scope to get pending jobs.
     */
    public function scopePending($query)
    {
        return $query->where('status', 'pending');
    }

    /**
     * Scope to get running jobs.
     */
    public function scopeRunning($query)
    {
        return $query->where('status', 'running');
    }

    /**
     * Scope to get failed jobs.
     */
    public function scopeFailed($query)
    {
        return $query->where('status', 'failed');
    }

    /**
     * Mark job as queued.
     */
    public function markAsQueued(): void
    {
        $this->update([
            'status' => 'queued',
            'started_at' => now(),
        ]);
    }

    /**
     * Mark job as running with comfy prompt ID.
     */
    public function markAsRunning(string $promptId, array $resolvedWorkflow): void
    {
        $this->update([
            'status' => 'running',
            'comfy_prompt_id' => $promptId,
            'resolved_workflow_json' => $resolvedWorkflow,
        ]);
    }

    /**
     * Mark job as succeeded.
     */
    public function markAsSucceeded(): void
    {
        $this->update([
            'status' => 'succeeded',
            'finished_at' => now(),
        ]);
    }

    /**
     * Mark job as failed.
     */
    public function markAsFailed(string $errorMessage): void
    {
        $this->update([
            'status' => 'failed',
            'error_message' => $errorMessage,
            'finished_at' => now(),
        ]);
    }
}
